{% set name = "rstcheck" %}
{% set version = "4.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 565efb68a8bbed417a1d7b87dc3f0869b8910f471d9829a9fcb7f009bfc6c219

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - rstcheck = rstcheck:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - docutils >=0.7

test:
  imports:
    - rstcheck
  commands:
    - python -m rstcheck --help
    - pip check

about:
  home: https://pypi.org/project/rstcheck
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Checks syntax of reStructuredText and code blocks nested within it
  doc_url: https://pypi.org/project/rstcheck
  dev_url: https://github.com/myint/rstcheck

extra:
  recipe-maintainers:
    - kynan
