{% set name = "rstcheck" %}
{% set version = "6.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4f47d1e136e8dc7e6fd54d9679dbc1ed7c4d87b12e17d00003fccf4734e9ffdf

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - rstcheck = rstcheck._cli:main

requirements:
  host:
    - python >=3.6
    - pip
    - poetry
  run:
    - python >=3.6
    - pip
    - rstcheck-core
    - typer <0.5,>=0.3.2

test:
  imports:
    - rstcheck
  commands:
    - rstcheck --help
    - pip check

about:
  home: https://pypi.org/project/rstcheck
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Checks syntax of reStructuredText and code blocks nested within it
  doc_url: https://pypi.org/project/rstcheck
  dev_url: https://github.com/myint/rstcheck

extra:
  recipe-maintainers:
    - kynan
